<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { RouterLink, useRoute, useRouter } from 'vue-router';
import RecipeImageField from '@/components/RecipeImageField.vue';
import ErrorState from '@/components/ErrorState.vue';
import LoadingState from '@/components/LoadingState.vue';
import { useAuthStore } from '@/stores/auth';
import { deleteCookbook, fetchCookbook, fetchCookbookMembers, updateCookbook, updateCookbookMemberRole, type Cookbook, type CookbookMember } from '@/utils/cookbooks';

const route = useRoute(); const router = useRouter(); const authStore = useAuthStore();
const cookbook = ref<Cookbook | null>(null); const members = ref<CookbookMember[]>([]); const loading = ref(true); const error = ref(''); const saving = ref(false); const deleting = ref(false); const transferId = ref(''); const deleteName = ref(''); const deleteError = ref('');
const form = reactive({ name: '', slug: '', description: '', image: null as File | null });
async function load(): Promise<void> { const id = String(route.params.id); const result = await fetchCookbook(id, authStore.tokenType, authStore.accessToken); if (!result.ok) { error.value = result.message; loading.value = false; return; } cookbook.value = result.cookbook; if (result.cookbook.member_role !== 'owner') { error.value = 'Les paramètres du cookbook sont réservés à son propriétaire.'; loading.value = false; return; } form.name = result.cookbook.name; form.slug = result.cookbook.slug ?? ''; form.description = result.cookbook.description ?? ''; const memberResult = await fetchCookbookMembers(id, authStore.tokenType, authStore.accessToken); if (memberResult.ok) members.value = memberResult.data; loading.value = false; }
async function save(): Promise<void> { if (!cookbook.value) return; saving.value = true; const result = await updateCookbook(cookbook.value.id, form, authStore.tokenType, authStore.accessToken); if (result.ok) cookbook.value = result.cookbook; else error.value = result.message; saving.value = false; }
async function transfer(): Promise<void> { if (!cookbook.value || !transferId.value || !window.confirm('Transférer la propriété de ce cookbook ?')) return; saving.value = true; const result = await updateCookbookMemberRole(cookbook.value.id, Number(transferId.value), 'owner', authStore.tokenType, authStore.accessToken); if (result.ok) await router.push({ name: 'cookbook', params: { id: cookbook.value.id } }); else { error.value = result.message; saving.value = false; } }
async function remove(): Promise<void> { if (!cookbook.value || deleteName.value.trim() !== cookbook.value.name) { deleteError.value = 'Saisissez exactement le nom du cookbook.'; return; } deleting.value = true; const result = await deleteCookbook(cookbook.value.id, deleteName.value, authStore.tokenType, authStore.accessToken); if (result.ok) await router.push({ name: 'cookbooks' }); else { deleteError.value = result.message; deleting.value = false; } }
onMounted(() => { void load(); });
</script>
<template>
  <main class="settings-page"><RouterLink class="back-link" :to="{ name: 'cookbook', params: { id: route.params.id } }">Retour à l’accueil du cookbook</RouterLink><LoadingState v-if="loading" label="Chargement des paramètres..." /><ErrorState v-else-if="error" :message="error" /><template v-else-if="cookbook"><header class="page-heading"><p class="kicker">{{ cookbook.name }}</p><h1>Paramètres</h1><p>Informations générales et zone dangereuse.</p></header>
    <section class="settings-section" aria-labelledby="general-title"><h2 id="general-title">Informations générales</h2><form @submit.prevent="save"><label for="cookbook-settings-name">Nom</label><input id="cookbook-settings-name" v-model="form.name" :disabled="saving" required /><label for="cookbook-settings-slug">Slug</label><input id="cookbook-settings-slug" v-model="form.slug" :disabled="saving" /><label for="cookbook-settings-description">Description</label><textarea id="cookbook-settings-description" v-model="form.description" rows="4" :disabled="saving" /><RecipeImageField v-model="form.image" input-id="cookbook-settings-image" label="Image" :existing-image-url="cookbook.image_url" :disabled="saving" /><button class="primary" type="submit" :disabled="saving">{{ saving ? 'Enregistrement...' : 'Enregistrer' }}</button></form></section>
    <section class="danger-section" aria-labelledby="danger-title"><h2 id="danger-title">Zone dangereuse</h2><div class="danger-action"><h3>Transférer la propriété</h3><p>Cette action donne la gestion du cookbook à un autre membre.</p><label for="transfer-target">Nouveau propriétaire</label><select id="transfer-target" v-model="transferId"><option value="">Choisir un membre</option><option v-for="member in members.filter((item) => item.user.id !== cookbook!.owner.id)" :key="member.user.id" :value="String(member.user.id)">{{ member.user.name }}</option></select><button type="button" class="danger-secondary" :disabled="!transferId || saving" @click="transfer">Transférer</button></div><div class="danger-action"><h3>Supprimer le cookbook</h3><p>La suppression est définitive.</p><label for="delete-cookbook-name">Nom du cookbook pour confirmation</label><input id="delete-cookbook-name" v-model="deleteName" :disabled="deleting" /><p v-if="deleteError" class="error" role="alert">{{ deleteError }}</p><button type="button" class="danger" :disabled="deleting" @click="remove">{{ deleting ? 'Suppression...' : 'Supprimer définitivement' }}</button></div></section>
  </template></main>
</template>
<style scoped>.settings-page { width: 100%; max-width: 76rem; margin: 0 auto; }.back-link { color: #395330; font-weight: 700; }.page-heading { margin: 1.5rem 0; }.kicker { margin: 0 0 .35rem; color: #6b7b57; font-size: .8rem; font-weight: 700; text-transform: uppercase; }.page-heading h1 { margin: 0; }.page-heading p:last-child { color: #50634d; }.settings-section, .danger-section { padding: 1.25rem; border: 1px solid rgba(86,112,79,.18); border-radius: 1rem; }.settings-section form { display: grid; gap: .6rem; }.settings-section label, .danger-action label { font-weight: 700; }.settings-section input, .settings-section textarea, .danger-action input, .danger-action select { box-sizing: border-box; width: 100%; padding: .7rem; border: 1px solid #b9c5af; border-radius: .5rem; font: inherit; }.primary, .danger, .danger-secondary { width: fit-content; padding: .65rem .8rem; border: 1px solid #395330; border-radius: .5rem; background: #395330; color: #fffdf8; font: inherit; font-weight: 700; cursor: pointer; }.danger-section { margin-top: 1.5rem; border-color: #e2b3ad; }.danger-section h2, .danger-action h3 { color: #8f1e1e; }.danger-action { display: grid; gap: .5rem; margin-top: 1rem; padding: 1rem; border: 1px solid #e2b3ad; border-radius: .7rem; }.danger-secondary { background: transparent; color: #8f1e1e; border-color: #8f1e1e; }.danger { background: #8f1e1e; border-color: #8f1e1e; }.error { color: #8f1e1e; }button:disabled { cursor: wait; opacity: .55; }</style>
