<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { RouterLink, useRoute } from 'vue-router';
import EmptyState from '@/components/EmptyState.vue';
import ErrorState from '@/components/ErrorState.vue';
import LoadingState from '@/components/LoadingState.vue';
import PaginationControls from '@/components/PaginationControls.vue';
import RecipeCard from '@/components/RecipeCard.vue';
import SearchBar from '@/components/SearchBar.vue';
import { useAuthStore } from '@/stores/auth';
import { addRecipeToCookbook, fetchCookbook, removeRecipeFromCookbook, type Cookbook } from '@/utils/cookbooks';
import { fetchRecipes, type Recipe, type RecipePagination } from '@/utils/recipes';

const route = useRoute(); const authStore = useAuthStore(); const cookbook = ref<Cookbook | null>(null); const recipes = ref<Recipe[]>([]); const pagination = ref<RecipePagination | null>(null); const search = ref(''); const loading = ref(true); const error = ref(''); const removing = ref<string | null>(null); const selectedRecipe = ref(''); const publicRecipes = ref<Recipe[]>([]); const adding = ref(false);
const canEdit = () => cookbook.value?.member_role === 'owner' || cookbook.value?.member_role === 'editor';
async function load(page = 1): Promise<void> { loading.value = true; error.value = ''; const result = await fetchRecipes(authStore.tokenType, authStore.accessToken, page, 'all', search.value.trim(), { cookbook_id: String(route.params.id) }); if (result.ok) { recipes.value = result.recipes; pagination.value = result.pagination; } else error.value = result.message; loading.value = false; }
async function loadCookbook(): Promise<void> { const result = await fetchCookbook(String(route.params.id), authStore.tokenType, authStore.accessToken); if (result.ok) cookbook.value = result.cookbook; else error.value = result.message; await load(); }
async function openAdd(): Promise<void> { const result = await fetchRecipes(authStore.tokenType, authStore.accessToken, 1, 'mine'); if (result.ok) publicRecipes.value = result.recipes; }
async function addRecipe(): Promise<void> { if (!selectedRecipe.value) return; adding.value = true; const result = await addRecipeToCookbook(String(route.params.id), selectedRecipe.value, authStore.tokenType, authStore.accessToken); if (result.ok) { selectedRecipe.value = ''; await load(pagination.value?.current_page ?? 1); } else error.value = result.message; adding.value = false; }
async function removeRecipe(id: string): Promise<void> { if (removing.value) return; removing.value = id; const result = await removeRecipeFromCookbook(String(route.params.id), id, authStore.tokenType, authStore.accessToken); if (result.ok) await load(pagination.value?.current_page ?? 1); else error.value = result.message; removing.value = null; }
onMounted(() => { void loadCookbook(); });
</script>
<template><main class="cookbook-recipes"><RouterLink class="back-link" :to="{ name: 'cookbook', params: { id: route.params.id } }">Retour à l’accueil du cookbook</RouterLink><template v-if="cookbook"><header class="page-heading"><div><p class="kicker">{{ cookbook.name }}</p><h1>Recettes</h1><p>Les recettes de ce cookbook, avec recherche et pagination.</p></div><RouterLink v-if="canEdit()" class="primary-link" :to="{ name: 'recipe-create', query: { cookbook_id: cookbook.id } }">Nouvelle recette</RouterLink></header><SearchBar v-model="search" :disabled="loading" @submit="load(1)" /><div v-if="canEdit()" class="add-existing"><button type="button" @click="openAdd">Ajouter une recette existante</button><select v-model="selectedRecipe" :disabled="adding" aria-label="Recette à ajouter"><option value="">Choisir une recette</option><option v-for="recipe in publicRecipes" :key="recipe.id" :value="recipe.id">{{ recipe.title }}</option></select><button type="button" :disabled="!selectedRecipe || adding" @click="addRecipe">Ajouter</button></div></template><LoadingState v-if="loading" label="Chargement des recettes..." /><ErrorState v-else-if="error" :message="error" show-retry @retry="load" /><EmptyState v-else-if="recipes.length === 0" title="Aucune recette dans ce cookbook." description="Modifiez votre recherche ou ajoutez une recette." /><template v-else><div class="recipe-grid"><article v-for="recipe in recipes" :key="recipe.id"><RecipeCard :recipe="recipe" /><button v-if="canEdit()" type="button" class="remove" :disabled="removing !== null" @click="removeRecipe(recipe.id)">{{ removing === recipe.id ? 'Retrait...' : 'Retirer du cookbook' }}</button></article></div><PaginationControls v-if="pagination && pagination.last_page > 1" :pagination="pagination" :disabled="loading" @change="load" /></template></main></template>
<style scoped>.cookbook-recipes { width: 100%; max-width: 76rem; margin: 0 auto; }.back-link { color: #395330; font-weight: 700; }.page-heading { display: flex; align-items: end; justify-content: space-between; gap: 1rem; margin: 1.5rem 0; }.kicker { margin: 0 0 .35rem; color: #6b7b57; font-size: .8rem; font-weight: 700; text-transform: uppercase; }.page-heading h1 { margin: 0; }.page-heading p:last-child { color: #50634d; }.primary-link { padding: .65rem .8rem; border-radius: .55rem; background: #395330; color: #fffdf8; font-weight: 700; text-decoration: none; }.add-existing { display: flex; flex-wrap: wrap; gap: .5rem; margin: 1rem 0; }.add-existing button, .add-existing select { padding: .55rem .7rem; border: 1px solid #395330; border-radius: .5rem; background: transparent; font: inherit; }.add-existing button:last-child { background: #395330; color: #fffdf8; }.recipe-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 1rem; margin-top: 1.25rem; }.remove { margin-top: .5rem; padding: .45rem .6rem; border: 1px solid #8f1e1e; border-radius: .45rem; background: transparent; color: #8f1e1e; font: inherit; cursor: pointer; }@media (max-width: 42rem) { .page-heading { align-items: flex-start; flex-direction: column; }.recipe-grid { grid-template-columns: 1fr; } }</style>
