<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { RouterLink, useRoute, useRouter } from 'vue-router';
import Avatar from '@/components/Avatar.vue';
import EmptyState from '@/components/EmptyState.vue';
import ErrorState from '@/components/ErrorState.vue';
import LoadingState from '@/components/LoadingState.vue';
import RecipeCard from '@/components/RecipeCard.vue';
import { useAuthStore } from '@/stores/auth';
import { fetchCookbook, fetchCookbookMembers, fetchCookbookRecipes, fetchLatestCookbookMessages, type Cookbook, type CookbookMember, type CookbookMessage } from '@/utils/cookbooks';
import { fetchPlannedMeals, type PlannedMeal } from '@/utils/planning';
import type { Recipe } from '@/utils/recipes';

const route = useRoute(); const router = useRouter(); const authStore = useAuthStore();
const cookbook = ref<Cookbook | null>(null); const members = ref<CookbookMember[]>([]); const recipes = ref<Recipe[]>([]); const messages = ref<CookbookMessage[]>([]); const meals = ref<PlannedMeal[]>([]); const loading = ref(true); const error = ref('');
function dateKey(date: Date): string { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; }
function monday(date: Date): Date { const result = new Date(date); const day = result.getDay() || 7; result.setDate(result.getDate() - day + 1); return result; }
function addDays(date: Date, days: number): Date { const result = new Date(date); result.setDate(result.getDate() + days); return result; }
const weekLabel = computed(() => { const start = monday(new Date()); return `${start.toLocaleDateString('fr-FR', { day: 'numeric', month: 'short' })} – ${addDays(start, 6).toLocaleDateString('fr-FR', { day: 'numeric', month: 'short' })}`; });
async function load(): Promise<void> { loading.value = true; error.value = ''; const id = String(route.params.id); const cookbookResult = await fetchCookbook(id, authStore.tokenType, authStore.accessToken); if (!cookbookResult.ok) { error.value = cookbookResult.message; loading.value = false; return; } cookbook.value = cookbookResult.cookbook; const start = monday(new Date()); const [membersResult, recipesResult, messagesResult, mealsResult] = await Promise.all([fetchCookbookMembers(id, authStore.tokenType, authStore.accessToken), fetchCookbookRecipes(id, authStore.tokenType, authStore.accessToken), fetchLatestCookbookMessages(id, authStore.tokenType, authStore.accessToken), fetchPlannedMeals(dateKey(start), dateKey(addDays(start, 6)), authStore.tokenType, authStore.accessToken, id)]); if (membersResult.ok) members.value = membersResult.data; if (recipesResult.ok) recipes.value = recipesResult.data.slice(0, 3).map((recipe) => ({ ...recipe, source: null, author: null, is_favorite: false })); if (messagesResult.ok) messages.value = messagesResult.messages.slice(0, 3); if (mealsResult.ok) meals.value = mealsResult.meals; loading.value = false; }
onMounted(() => { if (route.hash === '#cookbook-settings') { void router.replace({ name: 'cookbook-settings', params: { id: route.params.id } }); return; } if (route.hash === '#cookbook-members') { void router.replace({ name: 'cookbook-members', params: { id: route.params.id } }); return; } void load(); });
</script>

<template>
  <main class="cookbook-home"><LoadingState v-if="loading" label="Chargement du cookbook..." /><ErrorState v-else-if="error" :message="error" show-retry @retry="load" /><template v-else-if="cookbook">
    <header class="cookbook-hero"><div><p class="kicker">Accueil du cookbook</p><h1>{{ cookbook.name }}</h1><p class="description">{{ cookbook.description || 'Votre espace collaboratif de recettes.' }}</p></div><div class="hero-actions"><RouterLink v-if="cookbook.member_role === 'owner' || cookbook.member_role === 'editor'" class="primary-link" :to="{ name: 'cookbook-settings', params: { id: cookbook.id } }">Modifier</RouterLink><RouterLink class="secondary-link" :to="{ name: 'cookbook-recipes', params: { id: cookbook.id } }">Voir les recettes</RouterLink></div></header>
    <div class="home-grid">
      <section class="home-card" aria-labelledby="info-title"><h2 id="info-title">Informations générales</h2><img v-if="cookbook.image_url" class="cookbook-image" :src="cookbook.image_url" :alt="`Image de ${cookbook.name}`" /><p>{{ cookbook.description || 'Aucune description.' }}</p><p class="muted">Votre rôle : {{ cookbook.member_role ?? 'Membre' }}</p></section>
      <section class="home-card" aria-labelledby="members-title"><div class="card-heading"><h2 id="members-title">Membres</h2><RouterLink :to="{ name: 'cookbook-members', params: { id: cookbook.id } }">Voir tout</RouterLink></div><div v-if="members.length" class="member-avatars"><div v-for="member in members.slice(0, 8)" :key="member.user.id" :title="member.user.name"><Avatar :src="member.user.avatar_url ?? null" :name="member.user.name" size="medium" /><span class="sr-only">{{ member.user.name }}</span></div></div><EmptyState v-else title="Aucun membre" description="" /></section>
      <section class="home-card recent-recipes-card" aria-labelledby="recipes-title"><div class="card-heading"><h2 id="recipes-title">Recettes récentes</h2><RouterLink :to="{ name: 'cookbook-recipes', params: { id: cookbook.id } }">Voir tout</RouterLink></div><div v-if="recipes.length" class="recipe-grid"><RecipeCard v-for="recipe in recipes" :key="recipe.id" :recipe="recipe" /></div><EmptyState v-else title="Aucune recette" description="Ce cookbook ne contient pas encore de recette." /></section>
      <section class="home-card" aria-labelledby="planning-title"><div class="card-heading"><h2 id="planning-title">Planning de la semaine</h2><RouterLink :to="{ name: 'cookbook-planning', params: { id: cookbook.id } }">Détail</RouterLink></div><p class="muted">{{ weekLabel }}</p><ul v-if="meals.length" class="compact-list"><li v-for="meal in meals.slice(0, 6)" :key="meal.id"><strong>{{ meal.recipe.title }}</strong><span>{{ meal.date }}</span></li></ul><EmptyState v-else title="Aucun repas planifié" description="" /></section>
      <section class="home-card" aria-labelledby="messages-title"><div class="card-heading"><h2 id="messages-title">Derniers messages</h2><RouterLink :to="{ name: 'cookbook-messages', params: { id: cookbook.id } }">Discussion</RouterLink></div><ul v-if="messages.length" class="compact-list"><li v-for="message in messages" :key="message.id"><strong>{{ message.author.name }}</strong><span>{{ message.content }}</span></li></ul><EmptyState v-else title="Aucun message" description="" /></section>
    </div>
  </template></main>
</template>

<style scoped>
.cookbook-home { width: 100%; max-width: 76rem; margin: 0 auto; }.cookbook-hero { display: flex; align-items: end; justify-content: space-between; gap: 1rem; margin-bottom: 1.25rem; }.kicker { margin: 0 0 .35rem; color: #6b7b57; font-size: .8rem; font-weight: 700; letter-spacing: .14em; text-transform: uppercase; }h1 { margin: 0; font-size: clamp(2rem, 4vw, 3rem); }.description { max-width: 50rem; margin: .4rem 0 0; color: #50634d; line-height: 1.5; }.hero-actions, .card-heading { display: flex; align-items: center; justify-content: space-between; gap: .7rem; }.primary-link, .secondary-link { display: inline-block; padding: .6rem .75rem; border-radius: .55rem; font-weight: 700; text-decoration: none; white-space: nowrap; }.primary-link { background: #395330; color: #fffdf8; }.secondary-link { border: 1px solid #395330; color: #395330; }.home-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 1rem; }.home-card { min-width: 0; padding: 1.15rem; border: 1px solid rgba(86,112,79,.18); border-radius: 1rem; background: rgba(255,253,248,.92); }.recent-recipes-card { grid-column: 1 / -1; }.home-card h2 { margin: 0; font-size: 1.2rem; }.card-heading a { color: #395330; font-weight: 700; }.cookbook-image { width: 100%; max-height: 10rem; margin: 1rem 0 .7rem; object-fit: cover; border-radius: .7rem; }.home-card p { color: #50634d; line-height: 1.5; }.member-avatars { display: flex; flex-wrap: wrap; gap: .65rem; margin-top: 1rem; }.recipe-grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: .65rem; margin-top: 1rem; }.recipe-grid :deep(.recipe-card) { padding: .7rem; }.recipe-grid :deep(.recipe-card .description), .recipe-grid :deep(.recipe-card .recipe-rating), .recipe-grid :deep(.recipe-card .recipe-author), .recipe-grid :deep(.recipe-card .tags) { display: none; }.compact-list { display: grid; gap: .65rem; margin: 1rem 0 0; padding: 0; list-style: none; }.compact-list li { display: flex; justify-content: space-between; gap: .75rem; padding-bottom: .55rem; border-bottom: 1px solid rgba(86,112,79,.14); }.compact-list span { overflow: hidden; color: #50634d; text-overflow: ellipsis; white-space: nowrap; }.sr-only { position: absolute; width: 1px; height: 1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; }@media (max-width: 48rem) { .cookbook-hero { align-items: flex-start; flex-direction: column; }.home-grid { grid-template-columns: 1fr; } }@media (max-width: 36rem) { .hero-actions { flex-wrap: wrap; }.recipe-grid { grid-template-columns: 1fr; } }
</style>
