<script setup lang="ts">
import { computed, nextTick, onMounted, reactive, ref } from 'vue';
import { RouterLink, useRoute } from 'vue-router';
import Avatar from '@/components/Avatar.vue';
import EmptyState from '@/components/EmptyState.vue';
import ErrorState from '@/components/ErrorState.vue';
import LoadingState from '@/components/LoadingState.vue';
import CookbookInvitationForm from '@/components/CookbookInvitationForm.vue';
import { useAuthStore } from '@/stores/auth';
import { fetchCookbook, fetchCookbookMembers, removeCookbookMember, updateCookbookMemberRole, type Cookbook, type CookbookMember } from '@/utils/cookbooks';
import { useDialogFocus } from '@/utils/dialogFocus';

const route = useRoute(); const authStore = useAuthStore(); const cookbook = ref<Cookbook | null>(null); const members = ref<CookbookMember[]>([]); const loading = ref(true); const error = ref(''); const drafts = reactive<Record<number, string>>({}); const pending = ref<{ type: 'role' | 'remove'; member: CookbookMember } | null>(null); const dialog = ref<HTMLElement | null>(null); const saving = ref(false);
const canManage = computed(() => cookbook.value?.member_role === 'owner');
function roleLabel(role: string): string { return ({ owner: 'Propriétaire', editor: 'Éditeur', reader: 'Lecteur', viewer: 'Lecteur', commenter: 'Commentateur', moderator: 'Modérateur' }[role] ?? role); }
function isOwner(member: CookbookMember): boolean { return cookbook.value?.owner.id === member.user.id; }
function askRole(member: CookbookMember): void { if (!canManage.value || isOwner(member) || drafts[member.user.id] === member.role) return; pending.value = { type: 'role', member }; void nextTick(() => dialog.value?.focus()); }
function askRemove(member: CookbookMember): void { if (!canManage.value || isOwner(member)) return; pending.value = { type: 'remove', member }; void nextTick(() => dialog.value?.focus()); }
function cancel(): void { if (!saving.value) pending.value = null; }
async function confirm(): Promise<void> { if (!pending.value || !cookbook.value) return; saving.value = true; const item = pending.value; const result = item.type === 'role' ? await updateCookbookMemberRole(cookbook.value.id, item.member.user.id, drafts[item.member.user.id] ?? item.member.role, authStore.tokenType, authStore.accessToken) : await removeCookbookMember(cookbook.value.id, item.member.user.id, authStore.tokenType, authStore.accessToken); if (result.ok) { pending.value = null; await load(); } else error.value = result.message; saving.value = false; }
async function load(): Promise<void> { loading.value = true; error.value = ''; const id = String(route.params.id); const [book, result] = await Promise.all([fetchCookbook(id, authStore.tokenType, authStore.accessToken), fetchCookbookMembers(id, authStore.tokenType, authStore.accessToken)]); if (book.ok) cookbook.value = book.cookbook; else error.value = book.message; if (result.ok) { members.value = result.data; result.data.forEach((member) => { drafts[member.user.id] = member.role; }); } else error.value = result.message; loading.value = false; }
useDialogFocus(dialog, computed(() => pending.value !== null), cancel); onMounted(() => { void load(); });
</script>
<template><main class="members-page"><RouterLink class="back-link" :to="{ name: 'cookbook', params: { id: route.params.id } }">Retour à l’accueil du cookbook</RouterLink><template v-if="cookbook"><header class="page-heading"><div><p class="kicker">{{ cookbook.name }}</p><h1>Membres</h1><p>Gérez les rôles et les accès à cet espace.</p></div></header><CookbookInvitationForm v-if="canManage" :cookbook-id="cookbook.id" /></template><LoadingState v-if="loading" label="Chargement des membres..." /><ErrorState v-else-if="error" :message="error" show-retry @retry="load" /><EmptyState v-else-if="members.length === 0" title="Aucun membre" description="Ce cookbook ne contient aucun membre." /><div v-else class="member-list"><article v-for="member in members" :key="member.user.id" class="member-row"><Avatar :src="member.user.avatar_url ?? null" :name="member.user.name" size="medium" /><div class="identity"><strong>{{ member.user.name }}</strong><span>{{ member.user.email }}</span></div><span class="role-badge">{{ roleLabel(member.role) }}</span><div v-if="canManage && !isOwner(member)" class="actions"><label class="sr-only" :for="`role-${member.user.id}`">Rôle de {{ member.user.name }}</label><select :id="`role-${member.user.id}`" v-model="drafts[member.user.id]" @change="askRole(member)"><option v-for="role in ['editor', 'reader', 'commenter', 'moderator']" :key="role" :value="role">{{ roleLabel(role) }}</option></select><button type="button" class="remove" @click="askRemove(member)">Supprimer</button></div><span v-else-if="isOwner(member)" class="owner-label">Propriétaire</span></article></div><div v-if="pending" class="dialog-backdrop" @click.self="cancel"><section ref="dialog" class="confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="confirm-title" tabindex="-1"><h2 id="confirm-title">{{ pending.type === 'role' ? 'Confirmer la promotion' : 'Confirmer la suppression' }}</h2><p>{{ pending.type === 'role' ? `Attribuer le rôle ${roleLabel(drafts[pending.member.user.id] ?? pending.member.role)} à ${pending.member.user.name} ?` : `Supprimer ${pending.member.user.name} de ce cookbook ?` }}</p><p v-if="error" class="error" role="alert">{{ error }}</p><div class="dialog-actions"><button type="button" class="primary" :disabled="saving" @click="confirm">Confirmer</button><button type="button" :disabled="saving" @click="cancel">Annuler</button></div></section></div></main></template>
<style scoped>.members-page { width: 100%; max-width: 76rem; margin: 0 auto; }.back-link { color: #395330; font-weight: 700; }.page-heading { margin: 1.5rem 0; }.kicker { margin: 0 0 .35rem; color: #6b7b57; font-size: .8rem; font-weight: 700; text-transform: uppercase; }.page-heading h1 { margin: 0; }.page-heading p:last-child { color: #50634d; }.member-list { display: grid; gap: .7rem; margin-top: 1.5rem; }.member-row { display: grid; grid-template-columns: auto minmax(0,1fr) auto minmax(16rem,auto); align-items: center; gap: 1rem; padding: 1rem; border: 1px solid rgba(86,112,79,.18); border-radius: .8rem; }.identity { display: grid; gap: .2rem; min-width: 0; }.identity span { overflow: hidden; color: #50634d; text-overflow: ellipsis; }.role-badge, .owner-label { padding: .3rem .55rem; border-radius: 999px; background: #edf4e8; color: #395330; font-size: .85rem; font-weight: 700; }.actions { display: flex; flex-wrap: wrap; justify-content: end; gap: .5rem; }.actions select, .actions button, .dialog-actions button { padding: .5rem .65rem; border: 1px solid #395330; border-radius: .45rem; background: transparent; font: inherit; }.actions .remove { border-color: #8f1e1e; color: #8f1e1e; }.dialog-backdrop { position: fixed; inset: 0; z-index: 30; display: grid; place-items: center; padding: 1rem; background: rgba(29,39,24,.45); }.confirm-dialog { width: min(100%, 30rem); padding: 1.5rem; border-radius: 1rem; background: #fffdf8; }.confirm-dialog h2 { margin-top: 0; }.dialog-actions { display: flex; justify-content: end; gap: .6rem; }.dialog-actions .primary { background: #395330; color: #fffdf8; }.error { color: #8f1e1e; }.sr-only { position: absolute; width: 1px; height: 1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; }@media (max-width: 48rem) { .member-row { grid-template-columns: auto minmax(0,1fr) auto; }.actions { grid-column: 1 / -1; justify-content: start; } }@media (max-width: 36rem) { .member-row { grid-template-columns: auto 1fr; }.role-badge, .owner-label { grid-column: 2; }.actions { grid-column: 1 / -1; } }</style>
